In [207]:
#1. Import the NUMPY package under the name np.

import numpy as np

In [208]:
#2. Print the NUMPY version and the configuration.

np.version.version

'1.16.2'

In [209]:
#3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable "a"
# Challenge: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

a = np.random.random((2,3,5))

In [210]:
#4. Print a.

print(a)    

[[[0.43223912 0.2106153  0.94032    0.54407935 0.48576478]
  [0.19218169 0.09834779 0.80607024 0.83592244 0.79643802]
  [0.77108784 0.75337097 0.58326817 0.63103013 0.54264105]]

 [[0.35274303 0.87710348 0.43459389 0.44751853 0.74530258]
  [0.07661819 0.91733485 0.09001211 0.24687658 0.40425915]
  [0.04031079 0.65007358 0.24726343 0.70126607 0.76957378]]]


In [211]:
#5. Create a 5x2x3 3-dimensional array with all values equaling 1.
#Assign the array to variable "b"

b = np.random.random((5,2,3))
b.fill(1)

In [212]:
print(b)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


In [213]:
#7. Do a and b have the same size? How do you prove that in Python code?

# ==> They don't
a.shape==b.shape

False

In [214]:
#8. Are you able to add a and b? Why or why not?

# ==> no, because they don't have the same shape

np.add(a,b)

ValueError: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 

In [215]:
#9. Transpose b so that it has the same structure of a (i.e. become a 2x3x5 array). Assign the transposed array to varialbe "c".

c=b.transpose(1,2,0)

In [216]:
#10. Try to add a and c. Now it should work. Assign the sum to varialbe "d". But why does it work now?

d=np.add(a,c)

In [217]:
#11. Print a and d. Notice the difference and relation of the two array in terms of the values? Explain.

print("array a = ",a)
print("")
print("array d = ",d)
print("")
print("1 has be added to all the value in a since b was composed with 1 only")

array a =  [[[0.43223912 0.2106153  0.94032    0.54407935 0.48576478]
  [0.19218169 0.09834779 0.80607024 0.83592244 0.79643802]
  [0.77108784 0.75337097 0.58326817 0.63103013 0.54264105]]

 [[0.35274303 0.87710348 0.43459389 0.44751853 0.74530258]
  [0.07661819 0.91733485 0.09001211 0.24687658 0.40425915]
  [0.04031079 0.65007358 0.24726343 0.70126607 0.76957378]]]

array d =  [[[1.43223912 1.2106153  1.94032    1.54407935 1.48576478]
  [1.19218169 1.09834779 1.80607024 1.83592244 1.79643802]
  [1.77108784 1.75337097 1.58326817 1.63103013 1.54264105]]

 [[1.35274303 1.87710348 1.43459389 1.44751853 1.74530258]
  [1.07661819 1.91733485 1.09001211 1.24687658 1.40425915]
  [1.04031079 1.65007358 1.24726343 1.70126607 1.76957378]]]

1 has be added to all the value in a since b was composed with 1 only


In [218]:
#12. Multiply a and c. Assign the result to e.

e=np.multiply(a,c)

In [219]:
#13. Does e equal to a? Why or why not?

print("no e must be equal to a since it's multiplyed 1")


no e must be equal to a since it's multiplyed 1


In [220]:
#14. Identify the max, min, and mean values in d. Assign those values to variables "d_max", "d_min", and "d_mean"

d_max = np.max(d)
d_min = np.min(d)
d_mean = np.mean(d)

print(d_max)
print(d_min)
print(d_mean)

1.9403199969824894
1.0403107907344293
1.520807564505579


In [221]:
#15. Now we want to label the values in d. First create an empty array "f" with the same shape (i.e. 2x3x5) as d using `np.empty`.

f=np.empty(d.shape)

In [226]:
"""
#16. Populate the values in f. For each value in d, if it's larger than d_min but smaller than d_mean, assign 25 to the corresponding value in f.
If a value in d is larger than d_mean but smaller than d_max, assign 75 to the corresponding value in f.
If a value equals to d_mean, assign 50 to the corresponding value in f.
Assign 0 to the corresponding value(s) in f for d_min in d.
Assign 100 to the corresponding value(s) in f for d_max in d.
In the end, f should have only the following values: 0, 25, 50, 75, and 100.
Note: you don't have to use Numpy in this question.
"""

for i in range(2):
    for j in range (3):
        for k in range (5):
            temp_d=d[i][j][k]
            temp_f=f[i][j][k]
            if d_min<temp_d<d_mean:
                temp_f=25
            elif d_mean<temp_d<d_max:
                temp_f=75
            elif temp_d==d_mean:
                temp_f=50
            elif temp_d==d_min:
                temp_f=0
            elif temp_d==d_max:
                temp_f=100

print(d)
print("")
print(f)

[[[1.43223912 1.2106153  1.94032    1.54407935 1.48576478]
  [1.19218169 1.09834779 1.80607024 1.83592244 1.79643802]
  [1.77108784 1.75337097 1.58326817 1.63103013 1.54264105]]

 [[1.35274303 1.87710348 1.43459389 1.44751853 1.74530258]
  [1.07661819 1.91733485 1.09001211 1.24687658 1.40425915]
  [1.04031079 1.65007358 1.24726343 1.70126607 1.76957378]]]

[[[ 25.  25. 100.  75.  25.]
  [ 25.  25.  75.  75.  75.]
  [ 75.  75.  75.  75.  75.]]

 [[ 25.  75.  25.  25.  75.]
  [ 25.  75.  25.  25.  25.]
  [  0.  75.  25.  75.  75.]]]
